Fix "call of overloaded 'lerp' is ambiguous"
lerp function in src/shapes/metrics_path.cpp was causing an error:
error: call of overloaded ‘lerp(float&, const float&, float&)’ is ambiguous

/usr/include/c++/9/cmath:1919:3: note: candidate: ‘constexpr long double std::lerp(long double, long double, long double)’
 1919 |   lerp(long double __a, long double __b, long double __t) noexcept
      |   ^~~~
/usr/include/c++/9/cmath:1915:3: note: candidate: ‘constexpr double std::lerp(double, double, double)’
 1915 |   lerp(double __a, double __b, double __t) noexcept
      |   ^~~~
/usr/include/c++/9/cmath:1911:3: note: candidate: ‘constexpr float std::lerp(float, float, float)’
 1911 |   lerp(float __a, float __b, float __t) noexcept
      |   ^~~~
../submodule/rive-cpp/src/shapes/metrics_path.cpp:247:7: note: candidate: ‘float lerp(float, float, float)’
  247 | float lerp(float from, float to, float f) { return from + f * (to - from); }
      |       ^~~~
ninja: build stopped: subcommand failed.

Function was renamed to calcLerp().